### ISSUE TITLE
Mejoras sobre proyecto de excepciones, y agregar proyecto de strings

### ISSUE THREAD

**Issue by delucas** [programacion-avanzada/workspace#86]
Todos estos issues refieren al mismo tema, y agregan uno nuevo:
https://github.com/programacion-avanzada/workspace/issues/73
https://github.com/programacion-avanzada/workspace/issues/68
https://github.com/programacion-avanzada/workspace/issues/38

Lo que haremos será:
- [ ] Agregar ejemplos de múltiples excepciones, como en #73 
- [ ] Renombar las pruebas segun #68, pero la opción con nombres válidos **sin guiones bajos**
- [ ] Agregar proyecto, README, y enlaces adicionales para demostrar el uso de String, segun #38

**Comment by delucas** [comment]
Referido en otro issue
